FROM node:8.9.4-alpine

# Set up volume folder
RUN mkdir -p /app/dist/javascripts
WORKDIR /app

# Copy files
COPY package.json yarn.lock webpack.config.js ./
COPY src ./src/

# Install yarn
RUN apk update && \
  apk add yarn && \
  yarn install && \
  yarn global add webpack@3.8.1

CMD ["webpack"]
