FROM node:8.9.4-alpine

# Set up volume folder
WORKDIR /app

# Copy files
COPY docker.stylesheets.src /app/

# Install yarn
RUN apk update && \
  apk add yarn && \
  yarn global add gulp && \
  yarn install && \
  gulp

CMD ["gulp", "sass:watch"]
