FROM node:8.9.4-alpine

# Set up volume folder
WORKDIR /app

# Copy files
COPY docker.javascripts.src /app/

# Install yarn
RUN apk update && \
  apk add yarn && \
  yarn install && \
  yarn global add webpack@3.8.1

CMD ["webpack"]
