export const TABLES_FETCH_SUCCEEDED = 'TABLES_FETCH_SUCCEEDED';

export const CHANGE_TABLE = 'CHANGE_TABLE';

export const SET_QUERY = 'SET_QUERY';

export const QUERY_EXECUTION_SUCCEEDED = 'QUERY_EXECUTION_SUCCEEDED';
