export const TABLES_FETCH_SUCCEEDED = 'TABLES_FETCH_SUCCEEDED';

export const CHANGE_TABLE = 'CHANGE_TABLE';

export const SET_QUERY = 'SET_QUERY';

// row state
export const QUERY_EXECUTION_SUCCEEDED = 'QUERY_EXECUTION_SUCCEEDED';
export const TABLE_ROWS_FETCH_SUCCEEDED = 'TABLE_ROWS_FETCH_SUCCEEDED';

// credentialsErrorState
export const DB_CONNECTION_FAILED = 'DB_CONNECTION_FAILED';

// sqlErrorState
export const QUERY_EXECUTION_FAILED = 'QUERY_EXECUTION_FAILED'
